### ISSUE TITLE
Incorrect Reference to CLUDA

### ISSUE THREAD

**Issue by oezyurty** [mims-harvard/Raincoat#1]
First of all, many thanks for considering CLUDA in your paper! And of course, all the best wishes for your submission! 

Currently, in your GitHub repo the link of CLUDA incorrectly refers to the paper AdvSKM. May I kindly ask you to fix it? It will be published at ICLR 2023, but before that you can also refer to either openreview or arXiv link of the corresponding paper. 

Best,

**Comment by hehuannb** [comment]
Hi,

Thank you for pointing it out. The reference has been corrected. 

Best
