### ISSUE TITLE
Incorrect Implementation of DIRT-T ?

### ISSUE THREAD

**Issue by RomainMsrd** [mims-harvard/Raincoat#5]
First let me thank you for your amazing contribution. As stated in the title I see some incoherences between your DIRT-T implementation and the original paper.  Your implementation looks more like VADA, introduced in the same paper and which also serve as an initialization method for DIRT-T.

The authors describe DIRT-T as "a recursive extension of VADA, where the act of pseudo-labeling of the target distribution constructs a new 'source' domain". The problem is that I don't see neither the recursivity nor the pseudo-labelization. The classifier h_(n-1) is supposed to serve as teacher for h_n with h_0, the initial classifier, being the one produced by VADA.

I might have not understood your code well, if it is the case sorry for the inconvenience.

Best regards,

**Comment by hehuannb** [comment]
I will take a close look at DIRT-T again and come back to you. Thank you for your question!

**Comment by RomainMsrd** [comment]
I already had an answer from the authors' of Adatime. See discussion [here](https://github.com/emadeldeen24/AdaTime/issues/7#issuecomment-1687740584)
